### ISSUE TITLE
Patch for missing names in allCountries.txt

### ISSUE THREAD

**Issue by smadha** [chrismattmann/lucene-geo-gazetteer#19]
Locations in allCountries.txt are present with their official names. There are few locations which are more known by their popular names all over the world than their official names. 

Example -
- "Argentine Republic" as Argentina
- "Repubblica Italiana" as Italy

Possible way - Use country code list in geonames.org [0] and add a dummy document in lucene index for all PCLI.

[0] - http://download.geonames.org/export/dump/countryInfo.txt

**Comment by mubaldino** [comment]
Madhav, 
On our OpenSextant work we noted close to 1900 common name variations for some 250 countries and territories.  As Lucene is targeting a multilingual universe, so should these geo parsing tools.   Those 1900 names are in English/ASCII, native language and other languages.  How do you say "France" in  Greek?

but yes, you have the right idea -- each PCLI represents sovereign countries.  Some TERR (territories) are also have ISO 3166 codes.  So if you are trying to line up all country codes with official names and their variants, try both PCLI and TERR feature types.

-marc

**Comment by smadha** [comment]
@mubaldino 
Thanks for your input Marc. I wish I could do it for more categories ADM1, PPL, PPLC at very least but it's hard to find this data. For countries I could find data in countryInfo.txt which I can use. Do you know some other source?

Also can you share your OpenSextant work on common names?

With your comment rise a very interesting use case of taking language in consideration. As of now our app does not support different language, but it can be a very good feature.

Thanks
M

**Comment by chrismattmann** [comment]
ping @mubaldino @smadha is there a resolution here?

**Comment by mubaldino** [comment]
Madhav, 
Happy to share an approach and some sources here.  If I point you to our resources you'd become a bit entangled with our implementation.  After all, we are tackling nearly the same problem...

some approaches:

1. you have all you need in the data.  Country names in various languages are identified by feature class/code : "A/PLCI"  or non-independent entities as "A/PCL*".    Geonames (NGA's) records names for "Mongolia" such as the very uncommon: "Bügd Nayramdah Mongol Ard Uls" (A/PCLI)

2. http://download.geonames.org/export/dump/alternatenames/  -- Make use of this rich data set;  You would have to start with all A/PCL* entries in the full gazetteer and then find alternate names by place ID in these per-country alternate-name files.   There geonames.org did a nice job annotating each name with lang-id, etc.

In Xponents (under OpenSextant) I have worked out most of this implementation using Solr;  It would be nice to extend or enrich that with geonames.org content.   Not a priority for me right now,... But seems logical since you are using geonames.org as your main source.

Good luck,

Marc

**Comment by chrismattmann** [comment]
thanks @mubaldino will check it out

**Comment by smadha** [comment]
Thanks for your fantastic suggestions @mubaldino. In current algorithm, we do use alternate names but we don't leverage lang-id annotation. I think we can use locale information to know users preference and give better results. I'll go through annotations and think of some hook to add this information.

As of now I can think of adding another search field in lucene index say `local_name` and populate it as per mappings in http://download.geonames.org/export/dump/alternatenames/ for available system locale. Adding another dataset will increase time and space so will make it an optional  feature.

-
Madhav
