### ISSUE TITLE
Add a testing suite for location relevancy

### ISSUE THREAD

**Issue by smadha** [chrismattmann/lucene-geo-gazetteer#20]
Test suite must have diverse test cases covering continents, countries, states, cities, towns etc.. 

Consider using https://travis-ci.org/ 

Once we have this suite we can ensure future modifications don't disturb current classifiers.

**Comment by chrismattmann** [comment]
@smadha ping

**Comment by mubaldino** [comment]
Possible area of collaboration.  We have a relatively enormous evaluation data set internally.  Its simply not possible to release our evaluation data as a whole.  Lot of time developing "ground truth" for test and evaluation on specific data sets.  However, I would like to eventually (soon) release our toolkit for the evaluation data formats, guidelines for annotation of "truth" and scoring.   

Possible discussion if you like. 
Marc
Opensextant.org, 
MITRE

**Comment by chrismattmann** [comment]
hey Marc @mubaldino would be happy to have the discussion. How would you see this factoring into our test suite - would we be able to get some subsets of your dataset for evaluation?

**Comment by smadha** [comment]
A subset will help a lot. I originally thought of adding some regression test to make sure that any new change does not affect previous results.

**Comment by mubaldino** [comment]
If we work together on such a test data set it would be ideal to create a new top level project, either under ./chrismattmann/  or in our area ./OpenSextant.   ... or something completely new.  The mission under OpenSextant started out as focused solely on geo.    But getting time and funding to push big, reliable test data sets to the public is tough to secure.  If we start with a subset, it would be limited to about 100 rows for maybe 5-10 documents.   If I provide a subset for Eval work, I would likely start that under OpenSextant .... our eval was back in 2013 and have been growing that data set continuously. If I provide that it would be copyright under OpenSextant, ... and I'd welcome you to join that "eval" project as a contributor if you were interested.

Internally I had used 400 docs from our copy of LDC's "SpatialML" annotation set:
https://catalog.ldc.upenn.edu/LDC2008T03  --- in 2010 this was a fine starting point, however my review of the data revealed substantial holes and quality issues, despite their valiant efforts there.   Disclosure: the SpatialML work was done here at MITRE.

We'll have to agree on the schema, formats, some scripts, etc. Since we could both use this in the public domain it makes sense we consider how to do this once.   Resources like SpatialML are good models, however it would be easier to start over and make an attempt at developing very careful tests. 

looking forward to whatever we decide. it is all good.
Marc

**Comment by chrismattmann** [comment]
thank you @mubaldino and understood. I would be fine if the project was in OpenSextant - and happy to contribute - given that though can we please license the dataset under the ALv2 so we could use it in our project? Thanks and let me know.
