### ISSUE TITLE
Reverse geocoding using lucene-spatial

### ISSUE THREAD

**Issue by smadha** [chrismattmann/lucene-geo-gazetteer#23]
Aim - For a given latitude and longitude return name of city, state and country.

Lucene API - https://lucene.apache.org/core/5_0_0/spatial/index.html

**Comment by dsmiley** [comment]
You'll need a gazetteer of polygons.

I thought I'd share some open-source code that does this in Solr:
https://github.com/dsmiley/hhypermap-bop/tree/master/enrich/solr-geo-admin
That folder has the indexing & configuration side and embeds _some_ aspects of search (i.e. fetch of values via Lucene DocValues).  The search side is search by a point, basically.

**Comment by mubaldino** [comment]
You might consider how spatial fidelity plays into your processing concept.  Are you trying to support finding a closest city and gisting that reverse-lookup within 10KM radius, for example?  Or are you trying to get higher fidelity reverse-lookup, e.g., if a point is on some island or jetty or in some narrow slice of a province and you want positive location ID down below 1KM?

On OpenSextant we used the gazetteer itself (+Solr spatial).  Query ({!geofilt}) around a point and find what gazetteer features exist around that point.  Then sort on results by distance.  95% of the time that works for us and gets closest city, province, etc. within 10-20KM.  That approach provides worldwide lookups over or near land just using the gaz index.

If you are looking to provide a no-kidding solution that will do reverse lookup correctly 99.9%, then find some high-res shapefiles taking David's approach.  That is great because this could be adapted to maritime and areas where there is no gazetteer entries.

However, you get into much more data administration and size when you dive into the shapefile solution...  Last point to consider:  could you generalize this easily for world-wide coverage with shapefiles, and to what resolution and with what performance?

Interested to see where this heads.  You have some design & optimization choices to make, based on the audience you are trying to serve.

goodluck.

MarcU

**Comment by dsmiley** [comment]
Excellent input @mubaldino !

BTW I've been quite pleased with the approach in the H-Hypermap/BOP project.  Average response time is sub-millisecond with embedded Solr.  Before I got these results, I had ideas to improve it more but now see no need :-)

**Comment by smadha** [comment]
Thanks for your inputs @dsmiley and @mubaldino . I will look into these diligently and see how can I fit it in this project. 

My first thoughts were to use lucene-spatial for indexing latitude and longitude as `com.spatial4j.core.shape.Point` and then run below 2 steps -
1. Retrieve all locations inside `com.spatial4j.core.shape.Circle` formed through user provided coordinate as center and a configurable radius.
2. Rank retrieved results using existing ranking algorithm. 

However an interesting caveat is that geonames data have just one point for all type of location be it country or city it's just one point for all. I will see into polygon data. 

@mubaldino - For now I am looking for a straightforward implementation so 95% works. I think your suggestions are similar to above approach. 

Stay tuned :)

**Comment by chrismattmann** [comment]
This is merged
